version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    hostname: mongodb
    ports:
       - 27017:27017
    command: --smallfiles
  app:
    image: prabhakar747/spring-webflux-poc
    container_name: "webflux"
    ports:
       - 8080:8080
    hostname: app
    depends_on:
       - mongodb
    links:
       - mongodb
 